OMCPath (#317)
* [OMCPath] add class

* [OMCPath] add implementation using OMC via sendExpression()

* [OMCPath] add pytest (only docker at the moment)

* [OMCPath] TODO items

* [test_OMCPath] mypy fix

* [test_OMCPath] fix end of file

* [test_OMCPath] define test using OMCSessionZMQ() locally

* add TODO - need to check Python versions

* not working: 3.10
* working:     3.12

* [test_OMCPath] activate docker based on test_docker

* [OMCPath] add more functionality and docstrings

* [OMCPath] remove TODO entries

* [OMCPath] define limited compatibility for Python < 3.12

* use modified pathlib.Path as OMCPath

* [OMCSEssionZMQ] use OMCpath

* [OMCSessionZMQ] create a tempdir using omcpath_tempdir()

* [OMCPath] fix mypy

* [OMCPath] add warning message for Python < 3.12

* [OMCPath] try to make mypy happy ...

* [test_OMCPath] only for Python >= 3.12

* [test_OMCPath] update test

* [OMCPath._omc_resolve] use sendExpression() with parsed=False

* this is scripting output and, thus, it cannot be parsed

* [test_OMCPath] cleanup; use the same code for local OMC and docker based OMC

* [test_OMCPath] define test for WSL

* [test_OMCPath] use omcpath_tempdir() instead of hard-coded tempdir definition

* [OMCPath] spelling fix

see commit ID: aa74b367f0fa35b81905d646bbf1beefd3a89595 - [OMCPath] add more functionality and docstrings

* [OMCPath] implementation version 3

* differentiate between
  * Python >= 3.12 uses OMCPath based on OMC for filesystem operation
  * Python <  3.12 uses a pathlib.Path based implementation which is
    limited to OMCProcessLocal

* [OMCSession*] fix flake8 (PyCharm likes the empty lines)

* [OMCSessionZMQ] more generic definiton for omcpath_tempdir()

* [OMCPathCompatibility] mypy on github ...

* [OMCPathCompatibility] improve log messages

* [test_OMCPath] update

* [OMCPathReal] align exists() to the definition used in pathlib

* [test_OMCPath] fix error

error: "unlink" of "OMCPathReal" does not return a value (it only ever returns None)  [func-returns-value]

---------

Co-authored-by: Adeel Asghar <adeel.asghar@liu.se>